import streamlit as st
import pandas as pd
import joblib

# ---------------- PAGE SETTINGS ----------------
st.set_page_config(
    page_title="Vehicle CAN Attack Detection",
    page_icon="🚗",
    layout="centered"
)

st.title("🚗 Vehicle CAN Attack Detection System")
st.write("Random Forest-based CAN message attack detection")

st.info(
    "Enter the CAN message and vehicle parameters, "
    "then click Detect Attack."
)

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_model():
    return joblib.load("random_forest_model.pkl")

try:
    model = load_model()
except Exception as e:
    st.error(
        "Could not load random_forest_model.pkl. "
        "Make sure the model file is in the project folder."
    )
    st.stop()

# ---------------- INPUT FIELDS ----------------
st.subheader("Vehicle CAN Data")

with st.form("vehicle_data_form"):

    can_id = st.selectbox(
        "CAN ID",
        ["0x100", "0x101", "0x102", "0x103", "0x104"]
    )

    data_value = st.number_input(
        "CAN Data Value",
        min_value=0,
        max_value=1000,
        value=0,
        step=1
    )

    speed_value = st.number_input(
        "Vehicle Speed (km/h)",
        min_value=0,
        max_value=300,
        value=45,
        step=1
    )

    rpm_value = st.number_input(
        "Engine RPM",
        min_value=0,
        max_value=10000,
        value=1800,
        step=100
    )

    brake_value = st.selectbox(
        "Brake",
        [0, 1]
    )

    throttle_value = st.number_input(
        "Throttle",
        min_value=0,
        max_value=100,
        value=20,
        step=1
    )

    temperature_value = st.number_input(
        "Engine Temperature (°C)",
        min_value=0,
        max_value=200,
        value=80,
        step=1
    )

    detect_button = st.form_submit_button("Detect Attack")

# ---------------- RANDOM FOREST DETECTION ----------------
if detect_button:

    # Convert hexadecimal CAN ID to an integer
    can_id_number = int(can_id, 16)

    # Keep the same feature order used during model training
    input_data = pd.DataFrame(
        [[
            can_id_number,
            data_value,
            speed_value,
            rpm_value,
            brake_value,
            throttle_value,
            temperature_value
        ]],
        columns=[
            "can_id",
            "data",
            "speed",
            "rpm",
            "brake",
            "throttle",
            "engine_temperature"
        ]
    )

    # Predict using the trained Random Forest model
    prediction = model.predict(input_data)[0]

    # ---------------- DISPLAY RESULT ----------------
    st.subheader("Detection Result")

    if prediction == 1:
        st.error("🚨 ATTACK DETECTED: CAN Message Injection")
    else:
        st.success("✅ NORMAL TRAFFIC")

    st.caption(
        "Result generated by the trained Random Forest model. "
        "This is a software simulation, not a live vehicle security system."
    )